#!/bin/bash

##############################################################
#Ryan Whittingham
#CSE 224
#November 1, 2018
#Programming Assignment 3
#############################################################

###############  Program  Description  ########################
#Highlow is a game where the computer tries to guess the users 
#number in as few tries as possible.
################################################################  

floor=1  #lowest possible guess
ceiling=$1 #highest possible guess
response="x" #user's response to guess 
count=0 #total guesses

############### No command line argument given #############
if [[ "$ceiling" == "" ]]
then
	ceiling=100
fi
###############################################################

###################  Greeting  ################################
echo "------------------"
echo "Welcome to HighLow"
echo "------------------"
echo "Let's see how fast the computer can guess a number."
echo
echo "Think of a number between $floor and $ceiling."
echo "Press any key when you have it."
read -n 1 #read one character and continue
echo
echo
###################  Gameplay  #################################
while [[ "$response" != "c" ]]
do
	################  cheat detection  ####################
	if [[ $floor -gt $ceiling ]]
	then
		echo "----------------------------"
		echo "Are you sure that wasn't it?"
		echo "----------------------------" 
		echo "If $guess isn't your number, you must have changed your number in the middle of the game."
		echo
		echo "Unfortunately that's cheating."
		echo
		echo "Goodbye."
		echo
		exit
	#####################################################
	
	else
	
	################  CPU Guess  ##########################
		guess=$((($floor+$ceiling)/2))
		response="x"
		echo "----------------------"
		echo "Is your number $guess?"
		echo "----------------------"
		echo "Press h if that's too high."
		echo "Press l if that's too low."
		echo "Press c if that's your number."
		echo
	######################################################
	
	###############  User response  ########################	
		read -n 1 response #read one character and continue
		echo
		echo
	###########################################################

	##############  evaluate response  ########################  
		if [[ "$response" == "l" ]] #guess too low
		then
			floor=$((guess+1))
			count=$((count+1))
		
		elif [[ "$response" == "h" ]] #guess too high
		then
			ceiling=$((guess-1))
			count=$((count+1))
	
		elif [[ "$response" == "c" ]] #guess correct
		then
			count=$((count+1))
			echo "--------"
			echo "Hot dog!"
			echo "--------"
			echo "It took the computer $count times to guess your number."
			echo
		else
			echo
			echo "Invalid response." #not l, h, or c
			echo "Please try again."
			echo
		fi	
	fi
	#############################################################
done

######################################################################

echo "Thank you for playing."
echo
echo "Goodbye."
echo
exit
