#!/bin/bash

##############################################################
#Ryan Whittingham
#CSE 224
#October 4, 2018
#Programming Assignment 3
#############################################################

###############  Program  Description  ########################
#Highlow is a game where the CPU has to guess a number the user has choosen.
################################################################  

floor=0
ceiling=$1
response="x"
count=0
echo
echo "Welcome to HighLow"

if [[ "$ceiling" == "" ]]
then
	ceiling=100
fi

echo
echo "Think of a number between $floor and $ceiling."
echo "Press any key when you have it."
read -n 1
echo
echo
while [[ "$response" != "c" ]]
do
	if [[ $floor -gt $ceiling ]]
	then
		echo "If $guess isn't your number, then you must have switched your number."
		echo "That's against the rules."
		echo "Goodbye."
		echo
		exit
	else
		count=$((count+1))
		guess=$((($floor+$ceiling)/2))
		response="x"
		echo "Is your number $guess?"
		echo
			echo "Press h if that's too high."
			echo "Press l if that's too low."
			echo "Press c if that's your number."
			echo
			read -n 1 response
			echo
			echo

		if [[ "$response" == "l" ]]
		then
			echo "Too low you say."
			echo
			floor=$((guess+1))
		
		elif [[ "$response" == "h" ]]
		then
			echo "Too high you say."
			echo
			ceiling=$((guess-1))
	
		elif [[ "$response" == "c" ]]
		then
			echo "Correct you say!"
			echo "It took the CPU $count times to guess your number."
			echo
		else
			echo
			echo "Invalid response."
			echo "Please try again."
			echo
		fi	
		
	fi
done
echo "Goodbye."
echo
exit
